name: Test Actions 2
on: 
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'graph project name'
  release:
    types:
      - published

jobs:
  set-output:
    runs-on: ubuntu-latest
    steps: 
      - name: set output
        id: set
        shell: bash
        env: 
          TAGNAME: ${{ github.event.release.tag_name }}
        run: |
          TAG=${{ inputs.version }}
          echo "VERSION=${TAG#v}" >> $GITHUB_OUTPUT
      - name: output
        shell: bash
        run: echo "${{ steps.set.outputs.VERSION }}"
