name: Test Actions 2
on: 
  release:
    types:
      - published

jobs:
  set-output:
    runs-on: ubuntu-latest
    steps: 
      - name: set output
        id: set
        shell: bash
        run: |
          tagName = ${{ github.event.release.tag_name}}
      - name: output
        shell: bash
        run: echo "${{ steps.set.outputs.versionNumber }}"
