name: Test Actions 2
on: 
  workflow_dispatch:
    inputs:
  release:
    types:
      - published

jobs:
  set-output:
    runs-on: ubuntu-latest
    steps: 
      - name: set output
        id: set
        shell: bash
        run: |
          NAME=${{ github.event.repository.name }}
          echo "versionNumber=${NAME#test-}" >> $GITHUB_OUTPUT
      - name: output
        shell: bash
        run: echo "${{ steps.set.outputs.versionNumber }}"
