name: Test Actions 2
on: release

jobs:
  set-output:
    runs-on: ubuntu-latest
    steps: 
      - name: set output
        id: set
        shell: bash
        run: |
          "{versionNumber}={${ context.payload.release.tag_name:1}}" >> "$GITHUB_OUTPUT"
      - name: output
        shell: bash
        run: echo "${{ steps.set.outputs.versionNumber }}"
