name: Test Actions
on:
  workflow_dispatch:
    inputs:
      test:
        type: string
        default: "true"

jobs:
  set-output:
    runs-on: ubuntu-latest
    steps: 
      - name: output
        shell: bash
        run: echo "Test ${{ inputs.test == true && 'deploy2dev' || '' }}"
