name: Test Actions 2
on: 
  release:
    types:
      - published

jobs:
  set-output:
    runs-on: ubuntu-latest
    steps: 
      - name: set output
        id: set
        shell: bash
        env: 
          TAGNAME: ${{ github.event.release.tag_name }}
        run: |
          echo "versionNumber=${ TAGNAME:1 }" >> "$GITHUB_OUTPUT" 
      - name: output
        shell: bash
        run: echo "${{ steps.set.outputs.versionNumber }}"
