name: Test Actions
on:
  workflow_dispatch:
    inputs:
      test:
        type: string
        default: "true"

jobs:
  set-output:
    runs-on: ubuntu-latest
    env: 
      deploy2dev: 
    steps: 
      - name: output
        shell: bash
        run: |
          DEPLOY=${{ inputs.test }} == "false" && "deploy2dev" || ""
          echo "Test ${ DEPLOY }"
